#!/bin/bash

cmd=""
args="$@"
targettab="default"    # set this to the default tab name you want
profilename="Sublime"  # set this to the iTerm profile to use

if (( $# > 1 )); then
    targettab="$1"
    args="${@:2}"
fi

if [ -n "$args" ]; then
    cmd="$args"
fi

osascript &>/dev/null 2>&1 <<EOF
    tell application "iTerm"
        repeat with aWindow in windows
            repeat with aTab in tabs of aWindow
                tell current session of aTab
                    set candidate to (variable named "user.sublimetab")
                    if (candidate is "${targettab}") then
                        set responding to (is at shell prompt of current session of aTab)
                        -- set responding to false

                        if responding then
                        -- display dialog "responding tab"
                        tell aTab
                            select
                            activate
                            tell current session
                                write text ""
                                write text "${cmd}"
                                return
                            end tell
                        end tell
                        else
                            -- display dialog "closing dead tab"
                            set parentWindow to aWindow
                            tell aTab to close
                            exit repeat
                        end if
                    end if
                end tell
            end repeat
        end repeat
        if (count of windows) ≥ 1 then
            -- display dialog "existing window found"
            try
                tell parentWindow to set newtab to (create tab with profile "${profilename}")
            on error
                tell (last item of windows) to set newtab to (create tab with profile "${profilename}")
            end try
        else
            -- display dialog "no window"
            set newTab to (create window with profile "${profilename}")
        end if
        tell newTab
            select
            activate
            repeat while not (is at shell prompt of current session of newTab)
                delay 0.05
            end repeat
            tell current session of newTab
                -- don't merge this with semicolon or detection breaks
                write text "export SUBLIMETAB=${targettab}"
                write text "${cmd}"
            end tell
        end tell
        return
    end tell
EOF
